services:
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_PORT}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d tg_users -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5